[package]
name = "miniquad_async"
version = "0.1.0"
authors = ["Arif Driessen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
miniquad = {git = "https://github.com/not-fl3/miniquad"}
